[package]
name = "gitgov-rs"
version = "0.1.0"
authors = ["Mike Bush <platy@njk.onl>"]
edition = "2018"

[dependencies]
scraper = "0.12.0"
surf = "2.1.0"
lol_html = "0.2.0"
futures-lite = "1.11.2"

[dev-dependencies]
pretty_assertions = "0.6.1"
html-diff = "0.0.6"
html5ever = "0.25"
